### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'WARN:'

### ISSUE THREAD

**Issue by tzawlxih** [costales/gufw#19]
Error on execution in Arch / Gnome 3.38.1

Binary 20.04.1, and builded from source 20.10.0 both crash.

```
# python3 /usr/lib/python3.8/site-packages/gufw/gufw.py

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'WARN:'
```

**Comment by costales** [comment]
Hi, did you installed ufw-extras and/or mosh?
Best regards.

**Comment by tzawlxih** [comment]
Hi @costales, yes everything is installed:

```
$ pacman -Q | egrep "mosh|ufw"

gufw 20.04.1-2
mosh 1.3.2-12
ufw 0.36-3
ufw-extras 0.5-2
```

**Comment by costales** [comment]
Thanks for the info.

Marking it as duplicated of https://github.com/costales/gufw/issues/9
