### ISSUE TITLE
cannot access '/usr/lib/python*/site-packages/gufw/gufw.py': No such file or directory - Ubuntu 20.04

### ISSUE THREAD

**Issue by amitdhiman000** [costales/gufw#22]
Ubuntu 20.04
ufw 0.36
Copyright 2008-2015 Canonical Ltd.

```
user@user-pc:~/Downloads$ sudo gufw
/usr/bin/gufw: line 2: [: =: unary operator expected
ls: cannot access '/usr/lib/python*/site-packages/gufw/gufw.py': No such file or directory
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'ERROR:'
```

$ ls -l /usr/lib | grep python
drwxr-xr-x 27 root root 24576 May 8 07:20 python2.7
drwxr-xr-x 3 root root 4096 Apr 26 2018 python3
drwxr-xr-x 29 root root 20480 May 8 07:19 python3.6
drwxr-xr-x 31 root root 20480 Jul 25 08:39 python3.8

I have 4 different python versions installed.
python3.8 does have a site-packages directory inside it. but there is no such package gufw.

**Comment by costales** [comment]
Hi,

Update to the Gufw version 20.10 from the backports repositories.

Best regards.
--
Costales.
