### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by CloudyWhale** [costales/gufw#43]
when i try to run it my desktop asks for my password (like what happens when i run any other app that needs root priviliges) so I put it in and then nothing happens and when I run it in terminal the same thing happens exept I get this error: 
"Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/lib/python3.10/site-packages/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/lib/python3.10/site-packages/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/lib/python3.10/site-packages/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/lib/python3.10/site-packages/gufw/gufw/view/listening.py", line 47, in _show_report
    report = self.gufw.frontend.get_listening_report()
  File "/usr/lib/python3.10/site-packages/gufw/gufw/model/frontend.py", line 111, in get_listening_report
    return self.firewall.get_listening_report()
  File "/usr/lib/python3.10/site-packages/gufw/gufw/model/firewall.py", line 237, in get_listening_report
    return self.backend.get_listening_report()
  File "/usr/lib/python3.10/site-packages/gufw/gufw/model/ufw_backend.py", line 525, in get_listening_report
    return_report.append('%'.join([actual_protocol, descomponent_fields[0], descomponent_fields[1], descomponent_fields[2], policy]))
IndexError: list index out of range"
Distro: EndavourOS (Based off of arch)

**Comment by costales** [comment]
Hi, could you run this command and paste here the exit? Thanks

`sudo ufw show listening`

**Comment by CloudyWhale** [comment]
When I was waiting for a response I completely removed gufw and now that I reinstalled it it works perfectly without me having to run that command.
