### ISSUE TITLE
LM 20.3 /usr/bin/gufw: line 2: [: too many arguments

### ISSUE THREAD

**Issue by keceph** [costales/gufw#51]
Warpinator is borked.  gufw is borked. Both worked fine two days ago.  Problem started yesterday.  Update issue?

user@computer:~ $ gufw
/usr/bin/gufw: line 2: [: too many arguments
Error executing command as another user: Request dismissed
user@computer:~ $ sudo gufw
[sudo] password for user:               
/usr/bin/gufw: line 2: [: =: unary operator expected
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'WARN:'
user@computer:~ $ gufw --version
/usr/bin/gufw: line 2: [: too many arguments
Error executing command as another user: Request dismissed
user@computer:~ $ sudo gufw --version
/usr/bin/gufw: line 2: [: =: unary operator expected
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'WARN:'
user@computer:~ $

**Comment by costales** [comment]
Hi,
This looks an older Gufw version or maybe the not right Ubuntu version (?).
Could you tell me those please?
Best regards.
