### ISSUE TITLE
gufw do not open a window after entered korrect PW.

### ISSUE THREAD

**Issue by Steffevon** [costales/gufw#70]
Starting from GUI opens no screen and trying to start gufw from shell gives an error:

gufw
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 21, in <module>
    from gufw.view.gufw  import Gufw
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 18, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

----------------------------------
Seems to be looking for "module gi" 
gufw is already the newest version (22.04.0-0ubuntu1)"

Ubuntu 22.04.4 LTS
gnome 42.9
X11

"

**Comment by Steffevon** [comment]
Tried reinstall both via shell and via gui "synaptic" reinstall. No difference and the same problem.

**Comment by costales** [comment]
Hi, do you have the gi installed?

dpkg -l | grep python | grep gi

Best regards.
